services:


  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yaml
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      # Configuration pour les nginx settings
      - KONG_NGINX_WORKER_PROCESSES=auto
      - KONG_NGINX_WORKER_RLIMIT_NOFILE=65535
      - KONG_NGINX_WORKER_CONNECTIONS=16384
      # Configuration debug
      - KONG_LOG_LEVEL=debug
      - KONG_UPSTREAM_KEEPALIVE_IDLE_TIMEOUT=3600
      - KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS=10000
      # Configuration spécifique pour les SSE
      - KONG_NGINX_HTTP_PROXY_BUFFERING=off
      - KONG_NGINX_HTTP_PROXY_REQUEST_BUFFERING=off
      - KONG_NGINX_HTTP_PROXY_BUFFER_SIZE=128k
      - KONG_NGINX_HTTP_PROXY_BUFFERS=4 256k
      - KONG_NGINX_HTTP_PROXY_BUSY_BUFFERS_SIZE=256k
      - KONG_NGINX_HTTP_PROXY_CONNECT_TIMEOUT=300s
      - KONG_NGINX_HTTP_PROXY_READ_TIMEOUT=3600s
      - KONG_NGINX_HTTP_PROXY_SEND_TIMEOUT=3600s
      - KONG_NGINX_HTTP_CLIENT_BODY_TIMEOUT=3600s
      - KONG_NGINX_HTTP_KEEPALIVE_TIMEOUT=3600s
      - KONG_NGINX_HTTP_CLIENT_HEADER_TIMEOUT=60s
      - KONG_NGINX_HTTP_CHUNKED_TRANSFER_ENCODING=on
    volumes:
      - ./kong/config.yaml:/etc/kong/kong.yaml:ro
    depends_on:
      - obex-api
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
  auth:
    build:
      context: ./gotrue
      dockerfile: Dockerfile
    container_name: gotrue
    depends_on:
      - db
    expose:
      - 9999
    env_file:
      - .env
    # Ajouter un script d'entrée pour exécuter la migration puis démarrer le service
    entrypoint: ["/bin/sh", "-c", "gotrue migrate && gotrue serve"]

  # Base de données pour GoTrue
  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: obex
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: example